run:
  timeout: 1m
linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - gocognit
    - gocyclo
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - durationcheck
    - forcetypeassert
    - importas
    - nilerr
    - predeclared
    - thelper
    - tparallel
    - promlinter
    - bodyclose
    - godot
    - funlen
    - gocritic
    - prealloc
    - nlreturn
    - unparam
