run:
  timeout: 1m

linters-settings:
  dogsled:
    max-blank-identifiers: 3
  lll:
    line-length: 90
    tab-width: 1
  revive:
    rules:
      - name: empty-lines

linters:
  enable:
    - bodyclose
    - containedctx
    - dogsled
    - errname
    - gocritic
    - gofmt
    - gosec
    - lll
    - nilerr
    - revive
    - unparam
    - wsl
